# -*- coding: utf-8 -*-
"""FlaskAPIcomDjango.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13dLmTkwBeEbrlmrxZvCUB9SBFxnmqsKI
"""

pip install django

!django-admin startproject portfolio

# Commented out IPython magic to ensure Python compatibility.
# %cd portfolio

from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(8000)"))

ALLOWED_HOSTS = ['colab.research.google.com']

!python manage.py runserver 8000

pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request
from flask import jsonify
from flask import Flask
import random as rk

ntable = Flask(__name__)
run_with_ngrok(ntable)

data= [
    {
        "number": "1"
        "name": "mahesh"
        "age": "25"
        "city": "bangalore"
        "country": "india"
    }

    {
        "number": "2"
        "name": "alex"
        "age": "26"
        "city": "london"
        "country": "uk"
    }

    {
        "number": "3"
        "name": "david"
        "age": "27"
        "city": "san francisco"
        "country": "usa"
    }

    {
        "number": "4"
        "name": "john"
        "age": "28"
        "city": "toronto"
        "country": "canada"
    }

    {
        "number": "5"
        "name": "chris"
        "age": "29"
        "city": "paris"
        "country": "france"
    }
]

@app.route("/")

def home():
  return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK OUT PUT ADD '/output' TO THE URL.</h3></marquee>"

@app.route("/input")

def input():
  return jsonify(data)

@app.route('/output', methods=['GET', 'POST'])

def predJson():
  pred = r.choice(["positive", "negative"])
  nd= data
  nd["prediction"] = pred
  return jsonify(nd)

  app.run()